CREATE FUNCTION fGetFullNameByID(@ID_OWNER INT)
RETURNS NVARCHAR(150)
AS
BEGIN
	DECLARE @ID INT = @ID_OWNER
	DECLARE @FullName NVARCHAR(150) = (
	SELECT FIRST_NAME + ' ' + LAST_NAME
	FROM dbo.OWNER
	WHERE ID = @ID);
	RETURN @FullName;
END;

DECLARE @OWNER INT = 108;
SELECT @OWNER AS N'OWNER';
SELECT dbo.fGetFullNameByID(@OWNER) AS N'full name';