ALTER VIEW vCars
AS
SELECT O.FIRST_NAME AS »Ãﬂ, O.LAST_NAME AS ‘¿Ã»À»ﬂ, B.[NAME] AS Ã¿– ¿, M.[NAME] AS ÃŒƒ≈À‹
FROM CAR AS C
LEFT JOIN [OWNER] AS O
ON C.ID_OWNER=O.ID
LEFT JOIN MODEL AS M
ON C.ID_MODEL=M.ID
LEFT JOIN BRAND AS B
ON M.ID_BRAND=B.ID;

SELECT *
FROM vCars;

--DROP VIEW vCars;